name: Build and Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build and push Docker image
        env:
          DOCKER_BUILDKIT: 1
          PORT: ${{ secrets.PORT }} # Set PORT environment variable
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t myapp:latest .
          docker tag myapp:latest ${{ secrets.REGISTRY_URL }}/myapp:latest
          docker push ${{ secrets.REGISTRY_URL }}/myapp:latest

      - name: Deploy to ECS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          REGION: ${{ secrets.REGION }}
          PORT: ${{ secrets.PORT }} # Set PORT environment variable
        run: |
          ecs-cli compose --project-name myapp --file docker-compose.yml --ecs-params ecs-params.yml service up --container-name web
